package GUI;


import GUI.SubmitAssignment;
import GUI.StudentDashboard;
import database.AssignmentDAO;
import database.CourseDAO;
import database.StudentDAO;
import educational.Course;
import educational.Student;
import java.util.List;

public class AssignmentToAnswer extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AssignmentToAnswer.class.getName());
    private Student student;
    /**
     * Creates new form AssignmentToAnswer
     */
    public AssignmentToAnswer(Student student) {
        this.student = student;
        initComponents();
        
        List<String> studentCourseNames = StudentDAO.getCourseNamesForStudent(student.getUserID());

        MyCoursesMenu.removeAllItems(); 
        for (String courseName : studentCourseNames) {
            MyCoursesMenu.addItem(courseName);
        }
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        myAssignmentsMenu = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        assignmentQuestion = new javax.swing.JTextArea();
        answerButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MyCoursesMenu = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(700, 400));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel1.setText(" Assignments ");

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel2.setText("Choice Assignment To See The Question:");

        myAssignmentsMenu.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        myAssignmentsMenu.addActionListener(this::myAssignmentsMenuActionPerformed);

        assignmentQuestion.setEditable(false);
        assignmentQuestion.setColumns(20);
        assignmentQuestion.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        assignmentQuestion.setRows(5);
        jScrollPane1.setViewportView(assignmentQuestion);

        answerButton.setBackground(new java.awt.Color(0, 153, 0));
        answerButton.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        answerButton.setForeground(new java.awt.Color(255, 255, 255));
        answerButton.setText("Answer");
        answerButton.addActionListener(this::answerButtonActionPerformed);

        backButton.setBackground(new java.awt.Color(153, 0, 0));
        backButton.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel3.setText("Select Assignment:");

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel4.setText("Select Course:");

        MyCoursesMenu.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        MyCoursesMenu.addActionListener(this::MyCoursesMenuActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(myAssignmentsMenu, 0, 255, Short.MAX_VALUE)
                            .addComponent(MyCoursesMenu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(130, 130, 130))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(answerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(MyCoursesMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(myAssignmentsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerButtonActionPerformed
        this.dispose();
        new SubmitAssignment(student).setVisible(true);
    }//GEN-LAST:event_answerButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        new StudentDashboard(student).setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private boolean isCourseSelectedByUser = false;
    
    private void MyCoursesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyCoursesMenuActionPerformed
        
        if (!isCourseSelectedByUser) {
        
        isCourseSelectedByUser = true; 
        return;
        }
        
        String selectedCourse = (String) MyCoursesMenu.getSelectedItem();
        myAssignmentsMenu.removeAllItems(); 

        if (selectedCourse != null) {
            int courseId = CourseDAO.getCourseIdByName(selectedCourse); 
            List<String> assignments = CourseDAO.getAssignmentTitlesForStudentAndCourse(student.getUserID(), courseId);

            for (String title : assignments) {
                myAssignmentsMenu.addItem(title);
            }
        }
    }//GEN-LAST:event_MyCoursesMenuActionPerformed
    
    private boolean isAssignmentSelectedByUser = false;
    private void myAssignmentsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myAssignmentsMenuActionPerformed
        if (!isAssignmentSelectedByUser) {
        
            isAssignmentSelectedByUser = true; 
            return;
        }
        
        String selectedAssignment = (String) myAssignmentsMenu.getSelectedItem();
        String selectedCourse = (String) MyCoursesMenu.getSelectedItem();

        if (selectedAssignment != null && selectedCourse != null) {
            int courseId = CourseDAO.getCourseIdByName(selectedCourse);
            int assignmetId = AssignmentDAO.getAssignmentIdByTitle(selectedAssignment, courseId);
            String description = AssignmentDAO.getAssignmentDescription(assignmetId, courseId);
            assignmentQuestion.setText(description);
        }
    }//GEN-LAST:event_myAssignmentsMenuActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new AssignmentToAnswer().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> MyCoursesMenu;
    private javax.swing.JButton answerButton;
    private javax.swing.JTextArea assignmentQuestion;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> myAssignmentsMenu;
    // End of variables declaration//GEN-END:variables
}
