package GUI;


import GUI.DoctorDashboard;
import database.AssignmentDAO;
import database.CourseDAO;
import database.StudentDAO;
import educational.Doctor;
import educational.Student;
import java.util.List;
import javax.swing.JOptionPane;

public class CorrectAssignment extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CorrectAssignment.class.getName());

    /**
     * Creates new form CorrectAssignment
     */
    private Doctor doctor;
    public CorrectAssignment(Doctor doctor) {
        this.doctor = doctor;
        initComponents();
        
        List<String> studentNames = StudentDAO.getStudentsInDoctorCourses(doctor.getUserID());


        studentsMenu.removeAllItems();

        
        for (String student : studentNames) {
            studentsMenu.addItem(student);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studentsMenu = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        studentsAssignmentsMenu = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        answerArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        setGradeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        assignmentGrade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        studentCourses = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel1.setText("Student Assignments");

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel2.setText("Select Student: ");

        studentsMenu.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        studentsMenu.addActionListener(this::studentsMenuActionPerformed);

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel3.setText("Select Assignment:");

        studentsAssignmentsMenu.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        studentsAssignmentsMenu.addActionListener(this::studentsAssignmentsMenuActionPerformed);

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel5.setText("Answer:");

        answerArea.setColumns(20);
        answerArea.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        answerArea.setRows(5);
        jScrollPane1.setViewportView(answerArea);

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel6.setText("Set Grade:");

        setGradeButton.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        setGradeButton.setText("Set Grade");
        setGradeButton.addActionListener(this::setGradeButtonActionPerformed);

        backButton.setBackground(new java.awt.Color(153, 0, 0));
        backButton.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("BACK");
        backButton.addActionListener(this::backButtonActionPerformed);

        assignmentGrade.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel7.setText("Select Course:");

        studentCourses.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        studentCourses.addActionListener(this::studentCoursesActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studentsMenu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(studentsAssignmentsMenu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(assignmentGrade)
                            .addComponent(studentCourses, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(setGradeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(185, 185, 185))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(studentsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(studentCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(studentsAssignmentsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignmentGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setGradeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        new DoctorDashboard(doctor).setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    
        private boolean isStudentSelectedByUser = false;
    private void studentsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentsMenuActionPerformed
        if (!isStudentSelectedByUser) {
            isStudentSelectedByUser = true; 
            return;
        }

        String selectedStudentName = (String) studentsMenu.getSelectedItem();
        if (selectedStudentName == null) return;

        // bring student id form his selected username
        int studentId = StudentDAO.getStudentIdByName(selectedStudentName);

        // get courses doctor added and student registered in it
        List<String> courses = StudentDAO.getDoctorCoursesForStudent(doctor.getUserID(), studentId);

       
        studentCourses.removeAllItems();

        
        for (String courseName : courses) {
            studentCourses.addItem(courseName);
        }

    }//GEN-LAST:event_studentsMenuActionPerformed
        
    private boolean isCourseSelectedByUser = false;
    private void studentCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentCoursesActionPerformed
        if (!isCourseSelectedByUser) {
            isCourseSelectedByUser = true; 
            return;
        }
        // bring student id again
        String selectedStudentName = (String) studentsMenu.getSelectedItem();
        int studentId = StudentDAO.getStudentIdByName(selectedStudentName);


        // seelcted course to get id
        String selectedCourseName = (String) studentCourses.getSelectedItem();
        if (selectedCourseName == null) return;

        // bring id from delected
        int courseId = CourseDAO.getCourseIdByName(selectedCourseName);

        // bring courses that not corrected yet
        // جلب كل الـ assignments للطالب في الكورس المختار
        List<String> assignments = AssignmentDAO.getPendingAssignmentTitles(studentId, courseId);

        if (assignments == null || assignments.isEmpty()) {
            // لو اي حاله اتحققت يبقا فيه احتمالين مفيش اسيمنتات خالص في الكورس او فيه و متصحح بالفل هنا بعمل بتأكد من الحالتين
            boolean hasAnyAssignments = AssignmentDAO.hasAssignmentsInCourse(courseId);
            if (!hasAnyAssignments) {
                JOptionPane.showMessageDialog(this, "There are no assignments for this course yet!");
            } else {
                JOptionPane.showMessageDialog(this, "All assignments for this student are graded!");
            }
            studentsAssignmentsMenu.removeAllItems(); 
            return;
        }

        // 
        studentsAssignmentsMenu.removeAllItems();
        for (String title : assignments) {
            studentsAssignmentsMenu.addItem(title);
        }

    }//GEN-LAST:event_studentCoursesActionPerformed

    private boolean isAssignmnetSelectedByUser = false;
    private void studentsAssignmentsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentsAssignmentsMenuActionPerformed
        if (!isAssignmnetSelectedByUser) {
            isAssignmnetSelectedByUser = true; 
            return;
        }
        // bring student id again
        String selectedStudentName = (String) studentsMenu.getSelectedItem();
        int studentId = StudentDAO.getStudentIdByName(selectedStudentName);


        // selcted course to get id
        String selectedCourseName = (String) studentCourses.getSelectedItem();
        int courseId = CourseDAO.getCourseIdByName(selectedCourseName);
        
        String selectedAssignment = (String) studentsAssignmentsMenu.getSelectedItem();
        int assignmentId = AssignmentDAO.getAssignmentIdByTitle(selectedAssignment, courseId);

        if (AssignmentDAO.isSubmitted(studentId, assignmentId)) {
            // student submit the assignmnet
            String answer = AssignmentDAO.getSolution(studentId, assignmentId);
            answerArea.setText(answer); // view solution
            JOptionPane.showMessageDialog(this, "Submitted");
        } else {
            // student didn't submit the assignment
            answerArea.setText(""); // empty text
            JOptionPane.showMessageDialog(this, "Not submitted yet");
        }

    }//GEN-LAST:event_studentsAssignmentsMenuActionPerformed

    private void setGradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setGradeButtonActionPerformed
        String gradeText = assignmentGrade.getText();
        if (gradeText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a grade");
            return;
        }

        float grade;
        try {
            grade = Float.parseFloat(gradeText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid grade format");
            return;
        }

        // get student id
        String selectedStudentName = (String) studentsMenu.getSelectedItem();
        int studentId = StudentDAO.getStudentIdByName(selectedStudentName);

        // get course id
        String selectedCourseName = (String) studentCourses.getSelectedItem();
        int courseId = CourseDAO.getCourseIdByName(selectedCourseName);

        // get assignment id
        String selectedAssignment = (String) studentsAssignmentsMenu.getSelectedItem();
        int assignmentId = AssignmentDAO.getAssignmentIdByTitle(selectedAssignment, courseId);

        //get max grade
        float maxGrade = AssignmentDAO.getMaxGrade(assignmentId);

        //check grade validity
        if (grade > maxGrade) {
            JOptionPane.showMessageDialog(
                this,
                "Grade can't be greater than max grade (" + maxGrade + ")",
                "Invalid Grade",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // save grade
        AssignmentDAO.setGrade(studentId, assignmentId, grade);

        JOptionPane.showMessageDialog(this, "Grade set successfully");
        assignmentGrade.setText("");

    }//GEN-LAST:event_setGradeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new CorrectAssignment().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea answerArea;
    private javax.swing.JTextField assignmentGrade;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton setGradeButton;
    private javax.swing.JComboBox<String> studentCourses;
    private javax.swing.JComboBox<String> studentsAssignmentsMenu;
    private javax.swing.JComboBox<String> studentsMenu;
    // End of variables declaration//GEN-END:variables
}
