package GUI;


import GUI.login;
import educational.Doctor;



public class DoctorDashboard extends javax.swing.JFrame {

    /**
     * Creates new form DoctorDashboard
     */
    private Doctor doctor;
    public DoctorDashboard(Doctor doctor) {
        this.doctor = doctor;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coursesMenu = new javax.swing.JPopupMenu();
        createcourse = new javax.swing.JMenuItem();
        viewallcourses = new javax.swing.JMenuItem();
        assignmentsMenu = new javax.swing.JPopupMenu();
        createassignment = new javax.swing.JMenuItem();
        removeAssignmet = new javax.swing.JMenuItem();
        correctAssignment = new javax.swing.JMenuItem();
        assignments = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        coursesSetting = new javax.swing.JButton();
        assignmentSetting = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        createcourse.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        createcourse.setText("Create Course");
        createcourse.setFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 14));
        createcourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createcourse.setPreferredSize(new java.awt.Dimension(160, 30));
        createcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createcourseActionPerformed(evt);
            }
        });
        coursesMenu.add(createcourse);

        viewallcourses.setText("View All Courses");
        viewallcourses.setFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 14));
        viewallcourses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewallcourses.setPreferredSize(new java.awt.Dimension(160, 30));
        viewallcourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewallcoursesActionPerformed(evt);
            }
        });
        coursesMenu.add(viewallcourses);

        createassignment.setText("Create Assignment");
        createassignment.setFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 14));
        createassignment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createassignment.setPreferredSize(new java.awt.Dimension(130, 20));
        createassignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createassignmentActionPerformed(evt);
            }
        });
        assignmentsMenu.add(createassignment);

        removeAssignmet.setText("Remove Assignment");
        removeAssignmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAssignmetActionPerformed(evt);
            }
        });
        assignmentsMenu.add(removeAssignmet);

        correctAssignment.setText("Correct Assignment");
        correctAssignment.setFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 14));
        correctAssignment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        correctAssignment.setPreferredSize(new java.awt.Dimension(130, 20));
        correctAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctAssignmentActionPerformed(evt);
            }
        });
        assignmentsMenu.add(correctAssignment);

        assignments.setText("Assignments");
        assignments.setFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 14));
        assignments.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        assignments.setPreferredSize(new java.awt.Dimension(130, 20));
        assignments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentsActionPerformed(evt);
            }
        });
        assignmentsMenu.add(assignments);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel1.setText("Doctor Dashboard");

        coursesSetting.setBackground(new java.awt.Color(0, 0, 102));
        coursesSetting.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        coursesSetting.setForeground(new java.awt.Color(255, 255, 255));
        coursesSetting.setText("Courses");
        coursesSetting.setAutoscrolls(true);
        coursesSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursesSettingActionPerformed(evt);
            }
        });

        assignmentSetting.setBackground(new java.awt.Color(0, 0, 102));
        assignmentSetting.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        assignmentSetting.setForeground(new java.awt.Color(255, 255, 255));
        assignmentSetting.setText("Assignments");
        assignmentSetting.setToolTipText("");
        assignmentSetting.setAutoscrolls(true);
        assignmentSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentSettingActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(153, 0, 0));
        logoutButton.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(coursesSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(assignmentSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(308, 308, 308))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignmentSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coursesSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createcourseActionPerformed
        new CreateCourse(doctor).setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_createcourseActionPerformed

    private void coursesSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursesSettingActionPerformed
        int x = (coursesSetting.getWidth() - coursesMenu.getPreferredSize().width) / 2;
        coursesMenu.show(coursesSetting, x, coursesSetting.getHeight() + 10);

        
    }//GEN-LAST:event_coursesSettingActionPerformed

    private void assignmentSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentSettingActionPerformed
        int x = (assignmentSetting.getWidth() - assignmentsMenu.getPreferredSize().width) / 2;
        assignmentsMenu.show(assignmentSetting, x, assignmentSetting.getHeight()+10);

        
    }//GEN-LAST:event_assignmentSettingActionPerformed

    private void createassignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createassignmentActionPerformed
        new CreateAssignment(doctor).setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_createassignmentActionPerformed

    private void viewallcoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewallcoursesActionPerformed
        new ViewAllCoursesDO(doctor).setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_viewallcoursesActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        new login().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void correctAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctAssignmentActionPerformed
        this.dispose();
        new CorrectAssignment(doctor).setVisible(true);
    }//GEN-LAST:event_correctAssignmentActionPerformed

    private void removeAssignmetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAssignmetActionPerformed
        this.dispose();
        new RemoveAssignment(doctor).setVisible(true);
    }//GEN-LAST:event_removeAssignmetActionPerformed

    private void assignmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentsActionPerformed
        new ViewAssignmentsDO(doctor).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_assignmentsActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DoctorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DoctorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DoctorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DoctorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DoctorDashboard().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignmentSetting;
    private javax.swing.JMenuItem assignments;
    private javax.swing.JPopupMenu assignmentsMenu;
    private javax.swing.JMenuItem correctAssignment;
    private javax.swing.JPopupMenu coursesMenu;
    private javax.swing.JButton coursesSetting;
    private javax.swing.JMenuItem createassignment;
    private javax.swing.JMenuItem createcourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JMenuItem removeAssignmet;
    private javax.swing.JMenuItem viewallcourses;
    // End of variables declaration//GEN-END:variables
}
