package GUI;


import GUI.login;
import educational.Student;

public class StudentDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentDashboard.class.getName());

    /**
     * Creates new form NewJFrame
     */
    private Student student;
    public StudentDashboard(Student student) {
        this.student = student;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assignmentsMenu = new javax.swing.JPopupMenu();
        myAssignments = new javax.swing.JMenuItem();
        assignmentSolution = new javax.swing.JMenuItem();
        assignmentToAnswer = new javax.swing.JMenuItem();
        coursesMenu = new javax.swing.JPopupMenu();
        myCourses = new javax.swing.JMenuItem();
        Register = new javax.swing.JMenuItem();
        viewAllCourses = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        assignmetButtonMenu = new javax.swing.JButton();
        courseButtonMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();

        myAssignments.setText("My Assignments");
        myAssignments.setFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 14));
        myAssignments.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myAssignments.setPreferredSize(new java.awt.Dimension(160, 35));
        myAssignments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myAssignmentsActionPerformed(evt);
            }
        });
        assignmentsMenu.add(myAssignments);

        assignmentSolution.setText("Assignment Solution");
        assignmentSolution.setFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 14));
        assignmentSolution.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        assignmentSolution.setPreferredSize(new java.awt.Dimension(160, 35));
        assignmentSolution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentSolutionActionPerformed(evt);
            }
        });
        assignmentsMenu.add(assignmentSolution);

        assignmentToAnswer.setText("Assignment To Answer");
        assignmentToAnswer.setFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 14));
        assignmentToAnswer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        assignmentToAnswer.setPreferredSize(new java.awt.Dimension(160, 35));
        assignmentToAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentToAnswerActionPerformed(evt);
            }
        });
        assignmentsMenu.add(assignmentToAnswer);

        myCourses.setText("My Courses");
        myCourses.setFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 14));
        myCourses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myCourses.setPreferredSize(new java.awt.Dimension(160, 35));
        myCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myCoursesActionPerformed(evt);
            }
        });
        coursesMenu.add(myCourses);

        Register.setText("Register For Courses");
        Register.setFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 14));
        Register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Register.setPreferredSize(new java.awt.Dimension(160, 35));
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        coursesMenu.add(Register);

        viewAllCourses.setText("All Courses");
        viewAllCourses.setFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 14));
        viewAllCourses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewAllCourses.setPreferredSize(new java.awt.Dimension(160, 35));
        viewAllCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllCoursesActionPerformed(evt);
            }
        });
        coursesMenu.add(viewAllCourses);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 400));

        assignmetButtonMenu.setBackground(new java.awt.Color(0, 0, 102));
        assignmetButtonMenu.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        assignmetButtonMenu.setForeground(new java.awt.Color(255, 255, 255));
        assignmetButtonMenu.setText("Assignments");
        assignmetButtonMenu.setToolTipText("");
        assignmetButtonMenu.setAutoscrolls(true);
        assignmetButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmetButtonMenuActionPerformed(evt);
            }
        });

        courseButtonMenu.setBackground(new java.awt.Color(0, 0, 102));
        courseButtonMenu.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        courseButtonMenu.setForeground(new java.awt.Color(255, 255, 255));
        courseButtonMenu.setText("Courses");
        courseButtonMenu.setAutoscrolls(true);
        courseButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseButtonMenuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel1.setText("Student Dashboard");

        logoutButton.setBackground(new java.awt.Color(153, 0, 0));
        logoutButton.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(courseButtonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(assignmetButtonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(logoutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(201, 201, 201))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseButtonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignmetButtonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void assignmetButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmetButtonMenuActionPerformed
        int x = (assignmetButtonMenu.getWidth() - assignmentsMenu.getPreferredSize().width) / 2;
        assignmentsMenu.show(assignmetButtonMenu, x, assignmetButtonMenu.getHeight()+10);

        
    }//GEN-LAST:event_assignmetButtonMenuActionPerformed

    private void courseButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseButtonMenuActionPerformed
        int x = (courseButtonMenu.getWidth() - coursesMenu.getPreferredSize().width) / 2;
        coursesMenu.show(courseButtonMenu, x, courseButtonMenu.getHeight() + 10);

       
    }//GEN-LAST:event_courseButtonMenuActionPerformed

    private void viewAllCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllCoursesActionPerformed
        new ViewAllCourses(student).setVisible(true);  
        this.dispose();
    }//GEN-LAST:event_viewAllCoursesActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        new RegisterForCourse(student).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegisterActionPerformed

    private void myCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myCoursesActionPerformed
        new RegisteredCourses(student).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_myCoursesActionPerformed

    private void myAssignmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myAssignmentsActionPerformed
        new AllAssignments(student).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_myAssignmentsActionPerformed

    private void assignmentSolutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentSolutionActionPerformed
        new SubmitAssignment(student).setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_assignmentSolutionActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        new login().setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void assignmentToAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentToAnswerActionPerformed
        this.dispose();
        new AssignmentToAnswer(student).setVisible(true);
    }//GEN-LAST:event_assignmentToAnswerActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new StudentDashboard().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Register;
    private javax.swing.JMenuItem assignmentSolution;
    private javax.swing.JMenuItem assignmentToAnswer;
    private javax.swing.JPopupMenu assignmentsMenu;
    private javax.swing.JButton assignmetButtonMenu;
    private javax.swing.JButton courseButtonMenu;
    private javax.swing.JPopupMenu coursesMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JMenuItem myAssignments;
    private javax.swing.JMenuItem myCourses;
    private javax.swing.JMenuItem viewAllCourses;
    // End of variables declaration//GEN-END:variables
}
