package GUI;


import GUI.StudentDashboard;
import database.AssignmentDAO;
import database.CourseDAO;
import database.StudentDAO;
import educational.Student;
import java.util.List;
import javax.swing.JOptionPane;

public class SubmitAssignment extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SubmitAssignment.class.getName());
    private Student student;
    /**
     * Creates new form solutions
     */
    public SubmitAssignment(Student student) {
        this.student = student;
        initComponents();
        
        List<String> studentCourseNames = StudentDAO.getCourseNamesForStudent(student.getUserID());

        MyCoursesMenu.removeAllItems(); 
        for (String courseName : studentCourseNames) {
            MyCoursesMenu.addItem(courseName);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        assignmentAnswer = new javax.swing.JTextField();
        myAssignmentsMenu = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        backToQuestion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MyCoursesMenu = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel1.setText("Solutions");

        backButton.setBackground(new java.awt.Color(153, 0, 0));
        backButton.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        assignmentAnswer.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        myAssignmentsMenu.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        myAssignmentsMenu.setForeground(new java.awt.Color(0, 0, 153));
        myAssignmentsMenu.setMaximumRowCount(20);
        myAssignmentsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myAssignmentsMenuActionPerformed(evt);
            }
        });

        submitButton.setBackground(new java.awt.Color(0, 153, 0));
        submitButton.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel2.setText("Select assignment and answer it..");

        backToQuestion.setBackground(new java.awt.Color(153, 0, 0));
        backToQuestion.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        backToQuestion.setForeground(new java.awt.Color(255, 255, 255));
        backToQuestion.setText("Back To Assignments Again");
        backToQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToQuestionActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel3.setText("Select Assignment:");

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel4.setText("Select Course:");

        MyCoursesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyCoursesMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(assignmentAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(myAssignmentsMenu, 0, 239, Short.MAX_VALUE)
                                    .addComponent(MyCoursesMenu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(backToQuestion)
                        .addGap(241, 241, 241))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(MyCoursesMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myAssignmentsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(assignmentAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backToQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new StudentDashboard(student).setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_backButtonActionPerformed

    private boolean isAssignmentSelectedByUser = false;
    private void myAssignmentsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myAssignmentsMenuActionPerformed
        if (!isAssignmentSelectedByUser) {
        
            isAssignmentSelectedByUser = true; 
            return;
        }
        
        String selectedCourse = (String) MyCoursesMenu.getSelectedItem();
        String selectedAssignment = (String) myAssignmentsMenu.getSelectedItem();

        if (selectedCourse == null || selectedAssignment == null) return;

        int courseId = CourseDAO.getCourseIdByName(selectedCourse);
        int assignmentId = AssignmentDAO.getAssignmentIdByTitle(selectedAssignment, courseId);

            //check if student answered this assignmet will prevent him from writting
            if (AssignmentDAO.isSubmitted(student.getUserID(), assignmentId)) {
                JOptionPane.showMessageDialog(this, "You already submitted this assignment");

                assignmentAnswer.setEditable(false);        // منع الكتابة
            } else { //if not he will be able to answer
                assignmentAnswer.setText("");               // فاضية للكتابة
                assignmentAnswer.setEditable(true);         // السماح بالكتابة
            }

    }//GEN-LAST:event_myAssignmentsMenuActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
       
        int studentId = student.getUserID();
        String selectedCourse = (String) MyCoursesMenu.getSelectedItem();
        String selectedAssignment = (String) myAssignmentsMenu.getSelectedItem();
        int courseId = CourseDAO.getCourseIdByName(selectedCourse);
        int assignmentId = AssignmentDAO.getAssignmentIdByTitle(selectedAssignment, courseId);

        
        String answer = assignmentAnswer.getText().trim();

        // check submission
        if (AssignmentDAO.isSubmitted(studentId, assignmentId)) {
            JOptionPane.showMessageDialog(this, "You already submitted this assignment");
            return;
        }

        // submit
        boolean success = AssignmentDAO.submitAssignmentAnswer(studentId, assignmentId, answer);
        if (success) {
            JOptionPane.showMessageDialog(this, "Assignment submitted successfully");
            assignmentAnswer.setText("");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void backToQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToQuestionActionPerformed
        this.dispose();
        new AssignmentToAnswer(student).setVisible(true);
    }//GEN-LAST:event_backToQuestionActionPerformed
        
    private boolean isCourseSelectedByUser = false;
    private void MyCoursesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyCoursesMenuActionPerformed
        if (!isCourseSelectedByUser) {
        
        isCourseSelectedByUser = true; 
        return;
        }
        
        String selectedCourse = (String) MyCoursesMenu.getSelectedItem();
        myAssignmentsMenu.removeAllItems(); 

        if (selectedCourse != null) {
            int courseId = CourseDAO.getCourseIdByName(selectedCourse); 
            List<String> assignments = CourseDAO.getAssignmentTitlesForStudentAndCourse(student.getUserID(), courseId);

            for (String title : assignments) {
                myAssignmentsMenu.addItem(title);
            }
        }
    }//GEN-LAST:event_MyCoursesMenuActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new SubmitAssignment().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> MyCoursesMenu;
    private javax.swing.JTextField assignmentAnswer;
    private javax.swing.JButton backButton;
    private javax.swing.JButton backToQuestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> myAssignmentsMenu;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
